### ISSUE TITLE
support row- and column-level access control

### ISSUE THREAD

**Issue by zeddit** [stackabletech/trino-opa-authorizer#31]
I wonder if trino-opa-auth support row- or column-level data access control. 
for example, alice could only access `date` and `age` column of a specific table and bob could access more e.g. `salary` column.
for rows, alice could only access rows between `2020-01` to `2021-01`, but bob could access from `2019-01` to `2023-01`.

thanks.

**Comment by sbernauer** [comment]
Hi @zeddit, thanks for your interest!
Just beforehand, I want to inform you that there is some joined effort to get this into the upstream Trino project, mostly by Bloomberg in https://github.com/trinodb/trino/pull/17940 :) The version from the linked PR already has some improvements over this repo.
With that out of the way, there is the function https://github.com/stackabletech/trino-opa-authorizer/blob/5d36202f96f0257762ca1d579d80805998aaea7f/src/main/java/tech/stackable/trino/opa/OpaAuthorizer.java#L489
where you can grant or deny a query based on the columns it tries to access. So column-level data control is given.

You can use it something like this (pseudo code): Sadly we don't have an working example usage as of now.
```
allow {
    input.action.operation = "SelectFromColumns"
	input.context.identity.user = "alice"
    input.action.resource.table.catalogName = "iceberg"
    input.action.resource.table.schemaName = "myschema"
    input.action.resource.table.tableName = "mytable"

    # check that `input.action.resource.columns` only contains allowed columns, such as date and age.
}
```

In https://github.com/trinodb/trino/pull/17940 there is also https://github.com/trinodb/trino/pull/17940/files#diff-8ee5e094514215e5a7af0b9899df39e7d6b32c7cc5a4d9692260aac47d117088R406 `public Set<String> filterColumns(SystemSecurityContext context, CatalogSchemaTableName table, Set<String> columns)`, which further simplifies the usage.


As of the row-level support, there is https://github.com/trinodb/trino/blob/4846bdb4f4dde906b0b4ae1a88e8a569910aa5ad/core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java#L883 `List<ViewExpression> getRowFilters(SystemSecurityContext context, CatalogSchemaTableName tableName)`, which trino-opa-authorizer could implement - currently this is not supported. In this case OPA would return the filters that should be applied to any given table and users, in turn enabling your describe usecase.
The feature should (tm) not be too complicated. Happy about comments, especially if you would be interested adding such functionality.

All the best,
Sebastian

**Comment by zeddit** [comment]
great thanks for your patient reply. I will try and give you feedback, thanks again.
